name: Update Log List
on:
    schedule:
        # every day at 2:00 am
        -   cron: '0 2 * * *'
jobs:
    resources:
        name: Update log list
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-java@v2
                with:
                    distribution: 'zulu'
                    java-version: '11'

            -   name: Fetch latest log list
                run: ./gradlew updateLogList

            -   name: Push log list
                uses: test-room-7/action-update-file@v1
                with:
                    file-path: |
                        certificatetransparency/src/main/resources/log_list.json
                        certificatetransparency/src/main/resources/log_list.sig
                    commit-msg: Auto update log_list.json and log_list.sig
                    github-token: ${{ secrets.AUTO_UPDATE_GITHUB_TOKEN }}
